AllCops:
  RunRailsCops: true

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

# Offense count: 26
# Configuration parameters: AllowURI.
Style/LineLength:
  Max: 112

# Offense count: 1
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: false

Style/DotPosition:
  Description: Checks the position of the dot in multi-line method calls.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-multi-line-chains
  Enabled: true
  EnforcedStyle: trailing
  SupportedStyles:
  - leading
  - trailing

Style/MultilineOperationIndentation:
  Description: Checks indentation of binary operations that span more than one line.
  Enabled: true
  EnforcedStyle: indented
  SupportedStyles:
  - aligned
  - indented

